# Generated by Django 5.1.3 on 2024-12-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('temp', models.IntegerField()),
                ('description', models.TextField()),
                ('wind_speed', models.PositiveIntegerField()),
            ],
        ),
    ]
