# Generated by Django 5.1.3 on 2024-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='city',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Fargona', 'Fargona')], max_length=200),
        ),
    ]
